import React, { useState } from 'react';
import { X, Code, Image as ImageIcon } from 'lucide-react';

export default function CoworkPanel() {
  const [activeTab, setActiveTab] = useState(0);
  const tabs = [
    { name: 'plan.md', type: 'markdown' },
    { name: 'server.py', type: 'code' }
  ];

  if (tabs.length === 0) {
    return (
      <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'var(--bg-primary)' }}>
        <div style={{ textAlign: 'center', color: 'var(--text-muted)' }}>
          <ImageIcon size={48} style={{ margin: '0 auto 16px', opacity: 0.5 }} />
          <p>Files generated by agents will appear here</p>
        </div>
      </div>
    );
  }

  return (
    <div style={{ flex: 1, display: 'flex', flexDirection: 'column', height: '100%', background: 'var(--bg-secondary)', borderLeft: '1px solid var(--border-subtle)' }}>
      {/* Tab bar */}
      <div style={{ display: 'flex', borderBottom: '1px solid var(--border-subtle)', background: 'var(--bg-primary)' }}>
        {tabs.map((tab, idx) => (
          <div 
            key={idx}
            onClick={() => setActiveTab(idx)}
            style={{ 
              padding: '12px 24px', 
              display: 'flex', 
              alignItems: 'center', 
              gap: '8px',
              borderBottom: activeTab === idx ? '2px solid var(--accent-cyan)' : '2px solid transparent',
              background: activeTab === idx ? 'var(--bg-elevated)' : 'transparent',
              color: activeTab === idx ? 'var(--text-primary)' : 'var(--text-secondary)',
              cursor: 'pointer',
              fontSize: '0.875rem'
            }}
          >
            <Code size={16} />
            {tab.name}
            <button style={{ background: 'none', border: 'none', color: 'inherit', marginLeft: '8px', cursor: 'pointer', opacity: 0.5 }}>
              <X size={14} />
            </button>
          </div>
        ))}
      </div>
      
      {/* Content Area */}
      <div style={{ flex: 1, padding: '24px', overflowY: 'auto' }}>
        {tabs[activeTab].type === 'markdown' && (
          <div className="markdown-body">
            <h1>Execution Plan</h1>
            <p>This is a generated markdown preview.</p>
            <ul>
              <li>Step 1: Setup infrastructure</li>
              <li>Step 2: Build backend core</li>
              <li>Step 3: Build frontend shell</li>
            </ul>
          </div>
        )}
        
        {tabs[activeTab].type === 'code' && (
          <pre>
            <code>
{`from fastapi import FastAPI

app = FastAPI()

@app.get("/")
def read_root():
    return {"Hello": "World"}
`}
            </code>
          </pre>
        )}
      </div>
    </div>
  );
}
